### PR TITLE
Nodejs Week2 homework is ready for comments

### PR DESCRIPTION
**Pull request by aijazraja**

### CODE REVIEW

**Review by Ekamba — CHANGES_REQUESTED** [review]
Hi @aijazraja try to double check your meals queries they are  not working, also I will advice to use variables names names that are meaningful. For example if you write something like `mxprice` people will maybe not understand the meaning of `mxprice`.

**Comment by aijazraja** [comment]
Hi @Ekamba 
i have deleted package-lock.json and now meals queries are working for me.
can you check it now if it is working for you

**Comment by Ekamba** [comment]
> Hi @Ekamba
> i have deleted package-lock.json and now meals queries are working for me.
> can you check it now if it is working for you

If you just delete package-lock.json and you didn't not change your code, the result will be the same. But why did you comment your code and ask for reviewers to uncomment? That is not good at all 😕

**Comment by aijazraja** [comment]
Meal-router is working on my side locally on all queries so that's why I ask you to check it for you.. I did not what did you mean by comment and uncomment

**Comment by Ekamba** [comment]
> Meal-router is working on my side locally on all queries so that's why I ask you to check it for you.. I did not what did you mean by comment and uncomment

In your meal-router.js at line 26 you wrote this (`//Showing all meals, plese uncomment down to see different meal options.`). At line 30, 33-39, 44, 49,  if someone want to check that code he has to uncomment those lines.

**Comment by aijazraja** [comment]
oh yea i got it 
i will fix it.. sorry i could not get you before.. so I think i will do it by if else so any query can work

**Comment by aijazraja** [comment]
Hi @Ekamba
I have fixed the meal-router now . All queries are working now without uncomment

**Pull request merged**
